export type AccordionType = "content" | "layout" | ''
export type SourceAccordionType = "json" | "mjml" | ''
export type ImageAttributesAccordionType = "setting" | "dimension" | "border" | ''
export type HeroAttributesAccordionType = "setting" | "dimension" | "border" | ''
export type TextAttributesAccordionType = "setting" | "dimension" | "extra" | 'typography' | ''
export type ButtonAttributesAccordionType = "setting" | "dimension" | "extra" | 'typography' | 'border' | ''
